### ISSUE TITLE
run npScarf crashes

### ISSUE THREAD

**Issue by wingwingWY** [mdcao/npScarf#13]
Hello,
I run npScarf with nanopore reads for scaffolding spades assembly result.
my shell is:

$myexe/jsa.seq.sort -r -n --input $inputfa --output sort_spades.fasta   &> $outfile
bwa index sort_spades.fasta  &>> $outfile
bwa mem -t 20  -x ont2d  -a -Y sort_spades.fasta $reads >sort_spades.fasta.sam
$myexe/jsa.np.npscarf --input sort_spades.fasta.sam  --seqFile sort_spades.fasta --format sam  --spadesDir ../output_spades_rmLong/ --verbose --prefix=npScarf    &>> $outfile
 
 It crashes with error:

#Sort list of bridges
Starting scaffolding.......
Extending 0 to the rear
 Last of scaffold 0 extention is on contig 0 (1-NODE_1_length_44147_cov_8.432349): iterating among 57 bridges
...10-NODE_10_length_15495_cov_30.258980
Exception in thread "main" java.lang.NullPointerException
        at japsa.bio.hts.scaffold.ContigBridge.display(ContigBridge.java:777)
        at japsa.bio.hts.scaffold.ScaffoldGraphDFS.walk2(ScaffoldGraphDFS.java:378)
        at japsa.bio.hts.scaffold.ScaffoldGraphDFS.connectBridges(ScaffoldGraphDFS.java:261)
        at japsa.tools.bio.np.NPScarfCmd.main(NPScarfCmd.java:286)

**Comment by hsnguyen** [comment]
Thanks for reporting the bug!
I have changed the code back to its previous working state, please update and re-compile the package and see if it works. 
Cheers,
